from lib import *

CHAPTER = chapter(8, ("Technical Architecture", "المعمارية التقنية"),
    ("Mad3oom is built from deliberately plain parts: web pages without a framework, a managed Postgres platform, and a decision engine without "
     "dependencies. This chapter states what is verified, what principles shape it, and what is merely recommended.",
     "بُنيت مدعوم من أجزاء بسيطة عن قصد: صفحات ويب بلا إطار عمل، ومنصة Postgres مُدارة، ومحرك قرار بلا اعتماديات. ويبيّن هذا الفصل ما "
     "جرى التحقق منه، والمبادئ التي تشكّله، وما هو مجرد توصية."),
    [
    H2("Verified technical context", "السياق التقني المُتحقَّق منه"),
    TABLE([("Layer", "الطبقة"), ("What the repositories show", "ما تُظهره المستودعات")], [
        [("**Frontend**", "**الواجهة**"),
         ("Static HTML, CSS and JavaScript ES modules loaded directly by the browser, with no bundler and no framework; an Arabic-first, right-to-left interface with a language switch.",
          "HTML وCSS ووحدات JavaScript من نوع ES ثابتة تُحمَّل مباشرة في المتصفح، بلا مُجمِّع ولا إطار عمل؛ وواجهة عربية الأولوية من اليمين إلى اليسار مع مفتاح للغة.")],
        [("**Delivery**", "**النشر**"),
         ("Static files served by Vercel.",
          "ملفات ثابتة تقدّمها Vercel.")],
        [("**Backend services**", "**الخدمات الخلفية**"),
         ("Supabase, providing Postgres with row-level security, authentication, serverless Edge Functions in Deno, Realtime and scheduled jobs.",
          "Supabase، وتوفّر قاعدة Postgres مع أمان على مستوى الصفوف، والمصادقة، ودوال Edge Functions بلا خوادم بلغة Deno، وRealtime، ومهامّ مجدولة.")],
        [("**Business rules**", "**قواعد العمل**"),
         ("Concentrated in Postgres. Database functions are the write boundary and are designed to check the caller's identity.",
          "تتركز في Postgres. ودوال قاعدة البيانات هي حدّ الكتابة، وهي مصمَّمة لتفحص هوية المستدعي.")],
        [("**Intelligence**", "**الذكاء**"),
         ("SIE lives in its own repository as ES modules with no npm dependencies and runs inside Edge Functions. An AI gateway with a multi-provider registry serves other AI features.",
          "يقيم SIE في مستودعه الخاص وحداتِ ES بلا اعتماديات npm، ويعمل داخل دوال Edge Functions. وتخدم بوابة ذكاء اصطناعي ذات سجل متعدد المزوّدين ميزات الذكاء الاصطناعي الأخرى.")],
        [("**Repositories**", "**المستودعات**"),
         ("Three: the platform, the SIE engine, and the WhatsApp module.", "ثلاثة: المنصة، ومحرك SIE، ووحدة واتساب.")],
        [("**Quality tooling**", "**أدوات الجودة**"),
         ("Continuous integration runs tests, a drift check against an inventory of production, and code scanning. The platform also has database tests of access rules that run on a real Postgres built from a production-shaped schema snapshot, plus browser render tests; the SIE repository has 1,264 passing tests.",
          "يشغّل التكامل المستمر الاختبارات، وفحص انحراف مقابل جرد للإنتاج، وفحص الشيفرة. وللمنصة كذلك اختبارات قاعدة بيانات لقواعد الوصول تعمل على Postgres حقيقية مبنية من لقطة لمخطط يطابق الإنتاج، إضافة إلى اختبارات عرض في المتصفح؛ ولمستودع SIE ‎1,264 اختبارًا ناجحًا.")],
    ], widths=[20, 80], cls="compact",
        caption=("Technical context as documented in the repositories on 9 October 2026.", "السياق التقني كما توثّقه المستودعات في 9 أكتوبر 2026.")),

    H2("Conceptual architecture", "المعمارية المفاهيمية"),
    FIG("architecture", ("A conceptual overview of the layers. It is not a deployment, network or data-flow diagram, and it omits services that are not documented well enough to draw.",
                         "نظرة مفاهيمية على الطبقات. وهي ليست مخطط نشر ولا شبكة ولا تدفق بيانات، وتُغفل خدمات لا يتوافر لها توثيق كافٍ لرسمها.")),

    H2("Principles at work", "المبادئ قيد العمل"),
    TABLE([("Principle", "المبدأ"), ("How it appears today", "كيف يظهر اليوم"), ("Stage", "المرحلة")], [
        [("**Modularity**", "**النمطية**"),
         ("Frontend features are split into pure model modules, data modules and views. The engine is layered with provider interfaces. Workspace panels are registered, not hard-wired.",
          "تُقسَّم ميزات الواجهة إلى وحدات نموذج خالصة ووحدات بيانات وعروض. والمحرك متعدد الطبقات بواجهات مزوّدين. واللوحات في Workspace مسجَّلة وليست مرتبطة بالشيفرة."),
         ("{{E}}", "{{E}}")],
        [("**Clear interfaces**", "**واجهات واضحة**"),
         ("Database functions are the write boundary; channel adapters have a four-duty contract; the integration API is versioned; the Workspace bridge has a message protocol.",
          "دوال قاعدة البيانات هي حدّ الكتابة؛ ولمحوِّلات القنوات عقد من أربع مهام؛ وواجهة التكامل ذات إصدارات؛ وللجسر في Workspace بروتوكول رسائل."),
         ("{{E}}", "{{E}}")],
        [("**Separation of responsibilities**", "**فصل المسؤوليات**"),
         ("In SIE, deciding and writing are separate layers and only one layer writes. Workspace never writes: hosted pages do. Domain rules are designed to live in the database, not in the doors that reach it.",
          "في SIE تُفصل طبقتا القرار والكتابة ولا تكتب إلا طبقة واحدة. وWorkspace لا يكتب أبدًا: بل تكتب الصفحات المستضافة. وقواعد المجال مصمَّمة لتعيش في قاعدة البيانات لا في الأبواب المؤدية إليها."),
         ("{{E}}", "{{E}}")],
        [("**Maintainability and safe change**", "**قابلية الصيانة والتغيير الآمن**"),
         ("Migrations are additive and re-runnable with precondition checks, and recent ones carry rollback scripts. Drift is checked against production. The newest domains use optimistic concurrency and idempotency keys.",
          "الترحيلات إضافية وقابلة لإعادة التشغيل مع فحوص شروط مسبقة، وللأحدث منها سكربتات تراجع. ويُفحص الانحراف مقابل الإنتاج. وتستخدم المجالات الأحدث التزامنًا تفاؤليًا ومفاتيح تفرّد."),
         ("{{E}}", "{{E}}")],
        [("**Reproducible decisions**", "**قرارات قابلة لإعادة الإنتاج**"),
         ("The engine has no randomness, injects time and orders ties explicitly, so any decision can be replayed.",
          "لا عشوائية في المحرك، ويحقن الوقت، ويرتّب حالات التعادل صراحةً، فيمكن إعادة تشغيل أي قرار."),
         ("{{E}}", "{{E}}")],
        [("**One conversation core**", "**نواة محادثات واحدة**"),
         ("Idempotent message intake and leased, fenced delivery have been designed, written and tested on a production-shaped database. They are not yet used by live conversations.",
          "جرى تصميم آلية لاستقبال الرسائل بلا تكرار وتسليم بإيجار وتسوير، وكتابتها واختبارها على قاعدة بيانات تطابق شكل الإنتاج. ولم تستخدمها المحادثات الحية بعد."),
         ("{{D}}", "{{D}}")],
    ], widths=[22, 60, 18], cls="compact",
        caption=("Architectural principles and where they show in the code.", "المبادئ المعمارية وأين تظهر في الشيفرة.")),

    H2("Engineering direction", "التوجه الهندسي"),
    P("The items below are directions. None of them is a statement about the current system, and none is scheduled.",
      "البنود الآتية اتجاهات، وليس أي منها وصفًا للنظام الحالي، ولم يُجدوَل أي منها."),
    TABLE([("Direction", "الاتجاه"), ("Why", "السبب"), ("Type", "النوع")], [
        [("Reliable delivery of side effects through an outbox, workers, retries and visible failures.", "تسليم الآثار الجانبية بموثوقية عبر صندوق صادر وعمال وإعادة محاولة وإظهار للإخفاقات."),
         ("A failed email or webhook should be visible and retryable.",
          "ينبغي أن يكون البريد أو الويب هوك الفاشل ظاهرًا وقابلًا لإعادة المحاولة."),
         ("{{R}}", "{{R}}")],
        [("The conversation core as the single path for conversations.", "نواة المحادثات بوصفها المسار الوحيد للمحادثات."),
         ("One place for ordering, idempotency and delivery.",
          "موضع واحد للترتيب ومنع التكرار والتسليم."),
         ("{{R}}", "{{R}}")],
        [("Request identifiers, error tracking and synthetic checks.", "معرّفات للطلبات وتتبع للأخطاء وفحوص اصطناعية."),
         ("Operability must be designed in.",
          "لا بد من تصميم قابلية التشغيل منذ البداية."),
         ("{{R}}", "{{R}}")],
    ], widths=[34, 50, 16], cls="compact",
        caption=("Recommended engineering directions.", "اتجاهات هندسية موصى بها.")),
    NOTE("This chapter publishes no complete system diagram, no undocumented services, no deployed infrastructure inventory and no API contracts. "
         "Where a detailed architecture cannot be verified from the repositories, the paper stays at the conceptual level.",
         "لا ينشر هذا الفصل مخططًا كاملًا للنظام ولا خدمات غير موثَّقة ولا جردًا للبنية المنشورة ولا عقود واجهات. وحيث تتعذر الإحاطة بمعمارية "
         "تفصيلية من المستودعات، تبقى الورقة عند المستوى المفاهيمي.",
         kind="limit"),
])
