from lib import *

CHAPTER = chapter(8, ("Technical Architecture", "المعمارية التقنية"),
    ("Mad3oom is built from deliberately plain parts: web pages without a framework, a managed Postgres platform, and a decision engine without "
     "dependencies. This chapter states what is verified, what principles shape it, and what is merely recommended.",
     "بُنيت مدعوم من أجزاء بسيطة عن قصد: صفحات ويب بلا إطار عمل، ومنصة Postgres مُدارة، ومحرك قرار بلا اعتماديات. ويبيّن هذا الفصل ما "
     "جرى التحقق منه، والمبادئ التي تشكّله، وما هو مجرد توصية."),
    [
    H2("Verified technical context", "السياق التقني المُتحقَّق منه"),
    TABLE([("Layer", "الطبقة"), ("What the repositories show", "ما تُظهره المستودعات")], [
        [("**Frontend**", "**الواجهة**"),
         ("HTML, CSS and JavaScript ES modules loaded directly by the browser, with no bundler and no framework; about 90 pages; an Arabic-first, right-to-left interface with a language switch.",
          "HTML وCSS ووحدات JavaScript من نوع ES تُحمَّل مباشرة في المتصفح، بلا مُجمِّع ولا إطار عمل؛ نحو 90 صفحة؛ وواجهة عربية الأولوية من اليمين إلى اليسار مع مفتاح للغة.")],
        [("**Delivery**", "**النشر**"),
         ("Vercel serves the static files. Its configuration holds only redirects and rewrites, including those used for OAuth and MCP discovery.",
          "تقدّم Vercel الملفات الثابتة. ولا تحوي إعداداتها سوى إعادة التوجيه وإعادة الكتابة، ومنها ما يخص اكتشاف OAuth وMCP.")],
        [("**Backend services**", "**الخدمات الخلفية**"),
         ("Supabase: Postgres with row-level security, Auth, Edge Functions in Deno (about 55 in the platform repository), Realtime, and pg_cron and pg_net for scheduled and asynchronous work.",
          "Supabase: قاعدة Postgres مع أمان على مستوى الصفوف، والمصادقة، ودوال Edge Functions بلغة Deno (نحو 55 دالة في مستودع المنصة)، وRealtime، وpg_cron وpg_net للعمل المجدول وغير المتزامن.")],
        [("**Business rules**", "**قواعد العمل**"),
         ("Concentrated in Postgres. SECURITY DEFINER functions check the caller's identity, and the newest tables have no direct table access: they are reached only through such functions.",
          "تتركز في Postgres. وتفحص دوال SECURITY DEFINER هوية المستدعي، وليس للجداول الأحدث وصول مباشر: إذ لا يُتوصَّل إليها إلا عبر هذه الدوال.")],
        [("**Intelligence**", "**الذكاء**"),
         ("SIE lives in its own repository as ES modules with no npm dependencies and runs inside Edge Functions. An AI gateway with a multi-provider registry serves other AI features.",
          "يقيم SIE في مستودعه الخاص وحداتِ ES بلا اعتماديات npm، ويعمل داخل دوال Edge Functions. وتخدم بوابة ذكاء اصطناعي ذات سجل متعدد المزوّدين ميزات الذكاء الاصطناعي الأخرى.")],
        [("**Repositories**", "**المستودعات**"),
         ("Three: the platform, the SIE engine, and the WhatsApp module.", "ثلاثة: المنصة، ومحرك SIE، ووحدة واتساب.")],
        [("**Quality tooling**", "**أدوات الجودة**"),
         ("Continuous integration runs tests, a drift check against an inventory of production, and code scanning. The platform has 57 Node test files and 49 SQL test files that run on a real Postgres built from a production-shaped schema snapshot, plus browser render tests; the SIE repository has 1,264 passing tests.",
          "يشغّل التكامل المستمر الاختبارات، وفحص انحراف مقابل جرد للإنتاج، وفحص الشيفرة. وللمنصة 57 ملف اختبار Node و49 ملف اختبار SQL تعمل على Postgres حقيقية مبنية من لقطة لمخطط يطابق الإنتاج، إضافة إلى اختبارات عرض في المتصفح؛ ولمستودع SIE ‎1,264 اختبارًا ناجحًا.")],
    ], widths=[20, 80], cls="compact",
        caption=("Technical context as documented in the repositories on 9 October 2026.", "السياق التقني كما توثّقه المستودعات في 9 أكتوبر 2026.")),

    H2("Conceptual architecture", "المعمارية المفاهيمية"),
    FIG("architecture", ("A conceptual overview of the layers. It is not a deployment, network or data-flow diagram, and it omits services that are not documented well enough to draw.",
                         "نظرة مفاهيمية على الطبقات. وهي ليست مخطط نشر ولا شبكة ولا تدفق بيانات، وتُغفل خدمات لا يتوافر لها توثيق كافٍ لرسمها.")),

    H2("Principles at work", "المبادئ قيد العمل"),
    TABLE([("Principle", "المبدأ"), ("How it appears today", "كيف يظهر اليوم"), ("Stage", "المرحلة")], [
        [("**Modularity**", "**النمطية**"),
         ("Frontend features are split into pure model modules, data modules and views. The engine is layered with provider interfaces. Workspace panels are registered, not hard-wired.",
          "تُقسَّم ميزات الواجهة إلى وحدات نموذج خالصة ووحدات بيانات وعروض. والمحرك متعدد الطبقات بواجهات مزوّدين. واللوحات في Workspace مسجَّلة وليست مرتبطة بالشيفرة."),
         ("{{E}}", "{{E}}")],
        [("**Clear interfaces**", "**واجهات واضحة**"),
         ("Database functions are the write boundary; channel adapters have a four-duty contract; the integration API is versioned; the Workspace bridge has a message protocol.",
          "دوال قاعدة البيانات هي حدّ الكتابة؛ ولمحوِّلات القنوات عقد من أربع مهام؛ وواجهة التكامل ذات إصدارات؛ وللجسر في Workspace بروتوكول رسائل."),
         ("{{E}}", "{{E}}")],
        [("**Separation of responsibilities**", "**فصل المسؤوليات**"),
         ("In SIE, deciding and writing are separate layers and only one layer writes. Workspace never writes: hosted pages do. Domain rules live in the database, not in the doors that reach it.",
          "في SIE تُفصل طبقتا القرار والكتابة ولا تكتب إلا طبقة واحدة. وWorkspace لا يكتب أبدًا: بل تكتب الصفحات المستضافة. وقواعد المجال تعيش في قاعدة البيانات لا في الأبواب المؤدية إليها."),
         ("{{E}}", "{{E}}")],
        [("**Maintainability and safe change**", "**قابلية الصيانة والتغيير الآمن**"),
         ("Migrations are additive and re-runnable with precondition checks, and recent ones carry rollback scripts. Drift is checked against production. The newest domains use optimistic concurrency and idempotency keys.",
          "الترحيلات إضافية وقابلة لإعادة التشغيل مع فحوص شروط مسبقة، وللأحدث منها سكربتات تراجع. ويُفحص الانحراف مقابل الإنتاج. وتستخدم المجالات الأحدث التزامنًا تفاؤليًا ومفاتيح تفرّد."),
         ("{{E}}", "{{E}}")],
        [("**Reproducible decisions**", "**قرارات قابلة لإعادة الإنتاج**"),
         ("The engine has no randomness, injects time and orders ties explicitly, so any decision can be replayed.",
          "لا عشوائية في المحرك، ويحقن الوقت، ويرتّب حالات التعادل صراحةً، فيمكن إعادة تشغيل أي قرار."),
         ("{{E}}", "{{E}}")],
        [("**One conversation core**", "**نواة محادثات واحدة**"),
         ("A design for idempotent message intake and leased, fenced delivery has been written and tested on a production-shaped database. Its infrastructure was installed in production on 8 October 2026 with every feature flag closed, so no conversation flows through it yet.",
          "جرى تصميم وكتابة واختبار آلية لاستقبال الرسائل بلا تكرار وتسليم بإيجار وتسوير على قاعدة بيانات تطابق شكل الإنتاج. وقد ثُبِّتت بنيتها في الإنتاج بتاريخ 8 أكتوبر 2026 مع إغلاق كل أعلام التفعيل، فلا تمرّ بها أي محادثة بعد."),
         ("{{D}}", "{{D}}")],
    ], widths=[22, 60, 18], cls="compact",
        caption=("Architectural principles and where they show in the code.", "المبادئ المعمارية وأين تظهر في الشيفرة.")),

    H2("Recommendations and future directions", "توصيات واتجاهات مستقبلية"),
    P("The items below come from internal engineering reviews in September and October 2026. They are recommendations. None of them is a "
      "statement about the current system, and none is scheduled.",
      "تأتي البنود الآتية من مراجعات هندسية داخلية في سبتمبر وأكتوبر 2026. وهي توصيات، وليس أي منها وصفًا للنظام الحالي، ولم يُجدوَل أي منها."),
    TABLE([("Recommendation", "التوصية"), ("Why", "السبب"), ("Type", "النوع")], [
        [("Bring the full database baseline under version control and add a staging environment.", "إدخال خط الأساس الكامل لقاعدة البيانات تحت ضبط الإصدارات وإضافة بيئة تجريبية."),
         ("Core tables and many functions were created outside the migration history, so a database cannot be rebuilt from the repository alone.",
          "أُنشئت الجداول الأساسية ودوال كثيرة خارج تاريخ الترحيلات، فلا يمكن إعادة بناء قاعدة البيانات من المستودع وحده."),
         ("{{R}}", "{{R}}")],
        [("Pin and self-host front-end dependencies; add a content security policy and integrity checks.", "تثبيت اعتماديات الواجهة واستضافتها ذاتيًا، وإضافة سياسة أمان للمحتوى وفحوص سلامة."),
         ("Unpinned remote scripts and the absence of a content policy widen the impact of any upstream change or compromise.",
          "تتسع آثار أي تغيير أو اختراق في المصدر عند وجود سكربتات بعيدة غير مثبَّتة وغياب سياسة للمحتوى."),
         ("{{R}}", "{{R}}")],
        [("Replace fire-and-forget side effects in database triggers with an outbox, workers, retries and dead-letter handling.", "استبدال الآثار الجانبية العشوائية في المحفِّزات بصندوق صادر وعمال وإعادة محاولة ومعالجة للرسائل الفاشلة."),
         ("A failed email or webhook should be visible and retryable, never recorded as a success.",
          "ينبغي أن يكون البريد أو الويب هوك الفاشل ظاهرًا وقابلًا لإعادة المحاولة، لا مسجَّلًا على أنه نجح."),
         ("{{R}}", "{{R}}")],
        [("Make the conversation core the single path for conversations.", "جعل نواة المحادثات المسار الوحيد للمحادثات."),
         ("It removes parallel code paths for the same message and gives one place for ordering, idempotency and delivery.",
          "تزيل مسارات الشيفرة المتوازية للرسالة نفسها وتمنح موضعًا واحدًا للترتيب ومنع التكرار والتسليم."),
         ("{{R}}", "{{R}}")],
        [("Propagate the caller's identity into database rules for every API door.", "تمرير هوية المستدعي إلى قواعد قاعدة البيانات في كل باب واجهة."),
         ("The planned Relay API is designed this way, so one rulebook governs the interface and the API. Applying it elsewhere avoids authorization logic in application code.",
          "صُمِّمت واجهة Relay المخطَّطة على هذا النحو، فيحكم دستور قواعد واحد الواجهة والـ API. وتعميمه يجنّب منطق التفويض في شيفرة التطبيق."),
         ("{{R}}", "{{R}}")],
        [("Consolidate duplicated shared code across Edge Functions and keep a single canonical engine deployment path.", "توحيد الشيفرة المشتركة المكررة بين دوال Edge Functions وإبقاء مسار نشر معتمد واحد للمحرك."),
         ("Copies drift apart, and two engine versions in production at once make behavior hard to reason about.",
          "تتباعد النسخ، ووجود إصدارين من المحرك في الإنتاج معًا يصعّب فهم السلوك."),
         ("{{R}}", "{{R}}")],
        [("Add request identifiers, error tracking and synthetic checks.", "إضافة معرّفات للطلبات وتتبعًا للأخطاء وفحوصًا اصطناعية."),
         ("A system can appear healthy while a function fails; operability needs to be designed in.",
          "قد يبدو النظام سليمًا بينما تفشل دالة ما؛ ولا بد من تصميم قابلية التشغيل منذ البداية."),
         ("{{R}}", "{{R}}")],
        [("Separate unrelated products that share one database.", "فصل المنتجات غير المترابطة التي تتشارك قاعدة بيانات واحدة."),
         ("A fault or compromise in one product should not reach the data of the others.",
          "ينبغي ألا يصل عطل أو اختراق في منتج إلى بيانات المنتجات الأخرى."),
         ("{{R}}", "{{R}}")],
    ], widths=[34, 50, 16], cls="compact long",
        caption=("Recommended architectural improvements.", "تحسينات معمارية موصى بها.")),
    NOTE("This chapter publishes no complete system diagram, no undocumented services, no deployed infrastructure inventory and no API contracts. "
         "Where a detailed architecture cannot be verified from the repositories, the paper stays at the conceptual level.",
         "لا ينشر هذا الفصل مخططًا كاملًا للنظام ولا خدمات غير موثَّقة ولا جردًا للبنية المنشورة ولا عقود واجهات. وحيث تتعذر الإحاطة بمعمارية "
         "تفصيلية من المستودعات، تبقى الورقة عند المستوى المفاهيمي.",
         kind="limit"),
])
